version: '3'
services:
  wp:
    image: wordpress:6.0 
    # https://hub.docker.com/_/wordpress/
    container_name: wpui
    env_file: 
      - configuration.env
    ports:
      - 127.0.0.1:80:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project  
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    env_file: 
      - configuration.env
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp

  php:
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin
    env_file: 
      - configuration.env 
    ports:
      - 127.0.0.1:8080:80
    links:
      - db:db

  db:
    image: mysql:latest 
    # https://hub.docker.com/_/mysql/ 
    # or mariadb https://hub.docker.com/_/mariadb
    container_name: wpdb
    env_file: 
      - configuration.env 
    ports:
      - 127.0.0.1:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./db-entry:/docker-entrypoint-initdb.d 
      - db_data:/var/lib/mysql 
      
volumes:
  db_data:
