apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pma
  name: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pma
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: pma
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
        - name: PMA_HOST
          value: db
        - name: PMA_PORT
          value: "3306"
        image: phpmyadmin/phpmyadmin
        imagePullPolicy: ""
        name: pma
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
